// src/config/languages.js

/**
 * Central language configuration registry.
 * Adding a new language requires ONLY adding a new object to this array.
 * No other part of the codebase should ever hardcode a language name.
 */

export const LEARNING_LEVELS = [
  { code: "A1", label: "Beginner", description: "Basic phrases and everyday expressions" },
  { code: "A2", label: "Elementary", description: "Simple, routine communication" },
  { code: "B1", label: "Intermediate", description: "Familiar matters and travel situations" },
  { code: "B2", label: "Upper Intermediate", description: "Complex text and fluent interaction" },
  { code: "C1", label: "Advanced", description: "Flexible, effective language use" },
  { code: "C2", label: "Mastery", description: "Near-native precision and nuance" },
];

export const LANGUAGES = [
  {
    id: "german",
    slug: "german",
    name: "German",
    nativeName: "Deutsch",
    flag: "🇩🇪",
    locale: "de-DE",
    status: "available",
    tagline: "Speak the language of precision and poetry.",
    levels: LEARNING_LEVELS,
    hasTeacherDirectory: true,
    hasCertification: true,
  },
  {
    id: "french",
    slug: "french",
    name: "French",
    nativeName: "Français",
    flag: "🇫🇷",
    locale: "fr-FR",
    status: "comingSoon",
    tagline: "The language of art, cuisine, and diplomacy.",
    levels: LEARNING_LEVELS,
    hasTeacherDirectory: false,
    hasCertification: false,
  },
  {
    id: "spanish",
    slug: "spanish",
    name: "Spanish",
    nativeName: "Español",
    flag: "🇪🇸",
    locale: "es-ES",
    status: "comingSoon",
    tagline: "Connect with over 500 million speakers worldwide.",
    levels: LEARNING_LEVELS,
    hasTeacherDirectory: false,
    hasCertification: false,
  },
  {
    id: "italian",
    slug: "italian",
    name: "Italian",
    nativeName: "Italiano",
    flag: "🇮🇹",
    locale: "it-IT",
    status: "comingSoon",
    tagline: "The melody of art, history, and design.",
    levels: LEARNING_LEVELS,
    hasTeacherDirectory: false,
    hasCertification: false,
  },
  {
    id: "portuguese",
    slug: "portuguese",
    name: "Portuguese",
    nativeName: "Português",
    flag: "🇵🇹",
    locale: "pt-PT",
    status: "comingSoon",
    tagline: "A global language across four continents.",
    levels: LEARNING_LEVELS,
    hasTeacherDirectory: false,
    hasCertification: false,
  },
  {
    id: "dutch",
    slug: "dutch",
    name: "Dutch",
    nativeName: "Nederlands",
    flag: "🇳🇱",
    locale: "nl-NL",
    status: "comingSoon",
    tagline: "Direct, practical, and widely spoken in trade.",
    levels: LEARNING_LEVELS,
    hasTeacherDirectory: false,
    hasCertification: false,
  },
  {
    id: "swedish",
    slug: "swedish",
    name: "Swedish",
    nativeName: "Svenska",
    flag: "🇸🇪",
    locale: "sv-SE",
    status: "comingSoon",
    tagline: "Gateway to Scandinavian culture and design.",
    levels: LEARNING_LEVELS,
    hasTeacherDirectory: false,
    hasCertification: false,
  },
  {
    id: "norwegian",
    slug: "norwegian",
    name: "Norwegian",
    nativeName: "Norsk",
    flag: "🇳🇴",
    locale: "nb-NO",
    status: "comingSoon",
    tagline: "Fjords, folklore, and a friendly grammar.",
    levels: LEARNING_LEVELS,
    hasTeacherDirectory: false,
    hasCertification: false,
  },
  {
    id: "polish",
    slug: "polish",
    name: "Polish",
    nativeName: "Polski",
    flag: "🇵🇱",
    locale: "pl-PL",
    status: "comingSoon",
    tagline: "A rich Slavic language at Europe's heart.",
    levels: LEARNING_LEVELS,
    hasTeacherDirectory: false,
    hasCertification: false,
  },
  {
    id: "greek",
    slug: "greek",
    name: "Greek",
    nativeName: "Ελληνικά",
    flag: "🇬🇷",
    locale: "el-GR",
    status: "comingSoon",
    tagline: "The roots of philosophy, myth, and science.",
    levels: LEARNING_LEVELS,
    hasTeacherDirectory: false,
    hasCertification: false,
  },
  {
    id: "arabic",
    slug: "arabic",
    name: "Arabic",
    nativeName: "العربية",
    flag: "🇸🇦",
    locale: "ar-SA",
    status: "comingSoon",
    tagline: "Spoken across the Middle East and North Africa.",
    levels: LEARNING_LEVELS,
    hasTeacherDirectory: false,
    hasCertification: false,
  },
  {
    id: "urdu",
    slug: "urdu",
    name: "Urdu",
    nativeName: "اردو",
    flag: "🇵🇰",
    locale: "ur-PK",
    status: "comingSoon",
    tagline: "Poetic, expressive, and richly literary.",
    levels: LEARNING_LEVELS,
    hasTeacherDirectory: false,
    hasCertification: false,
  },
  {
    id: "hindi",
    slug: "hindi",
    name: "Hindi",
    nativeName: "हिन्दी",
    flag: "🇮🇳",
    locale: "hi-IN",
    status: "comingSoon",
    tagline: "One of the most spoken languages on Earth.",
    levels: LEARNING_LEVELS,
    hasTeacherDirectory: false,
    hasCertification: false,
  },
  {
    id: "japanese",
    slug: "japanese",
    name: "Japanese",
    nativeName: "日本語",
    flag: "🇯🇵",
    locale: "ja-JP",
    status: "comingSoon",
    tagline: "Precision, tradition, and modern innovation.",
    levels: LEARNING_LEVELS,
    hasTeacherDirectory: false,
    hasCertification: false,
  },
  {
    id: "chinese",
    slug: "chinese",
    name: "Chinese",
    nativeName: "中文",
    flag: "🇨🇳",
    locale: "zh-CN",
    status: "comingSoon",
    tagline: "The most widely spoken native language.",
    levels: LEARNING_LEVELS,
    hasTeacherDirectory: false,
    hasCertification: false,
  },
  {
    id: "korean",
    slug: "korean",
    name: "Korean",
    nativeName: "한국어",
    flag: "🇰🇷",
    locale: "ko-KR",
    status: "comingSoon",
    tagline: "An elegant script and a global cultural wave.",
    levels: LEARNING_LEVELS,
    hasTeacherDirectory: false,
    hasCertification: false,
  },
  {
    id: "russian",
    slug: "russian",
    name: "Russian",
    nativeName: "Русский",
    flag: "🇷🇺",
    locale: "ru-RU",
    status: "comingSoon",
    tagline: "A literary giant spanning eleven time zones.",
    levels: LEARNING_LEVELS,
    hasTeacherDirectory: false,
    hasCertification: false,
  },
  {
    id: "turkish",
    slug: "turkish",
    name: "Turkish",
    nativeName: "Türkçe",
    flag: "🇹🇷",
    locale: "tr-TR",
    status: "comingSoon",
    tagline: "A bridge language between Europe and Asia.",
    levels: LEARNING_LEVELS,
    hasTeacherDirectory: false,
    hasCertification: false,
  },
];

export const DEFAULT_LANGUAGE_ID = "german";

export const getLanguageById = (id) =>
  LANGUAGES.find((language) => language.id === id) ?? null;

export const getAvailableLanguages = () =>
  LANGUAGES.filter((language) => language.status === "available");